# Generated by Django 5.0.6 on 2024-06-29 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='birth_certificate',
            field=models.FileField(default='default/birth_certificate.pdf', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='death_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='passport_photos',
            field=models.FileField(default='default/passport_photos.jpg', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='proof_of_nationality',
            field=models.FileField(default='default/proof_of_nationality.pdf', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='residence_permit',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='sworn_statement',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
