# Generated by Django 5.0.6 on 2024-06-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_document_birth_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('id_card_image', models.ImageField(upload_to='missing_id_cards/')),
            ],
        ),
    ]
