# Generated by Django 5.0.6 on 2024-07-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='document',
            name='birth_certificate',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='passport_photos',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='proof_of_nationality',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
