# Generated by Django 5.0.6 on 2024-08-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_appointment_paid_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='static/documents/communication/')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='birth_certificate',
            field=models.FileField(upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='death_certificate',
            field=models.FileField(blank=True, null=True, upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='marriage_certificate',
            field=models.FileField(blank=True, null=True, upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='passport_photos',
            field=models.FileField(upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='proof_of_nationality',
            field=models.FileField(upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='residence_permit',
            field=models.FileField(blank=True, null=True, upload_to='static/documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sworn_statement',
            field=models.FileField(blank=True, null=True, upload_to='static/documents/'),
        ),
    ]
