# Generated by Django 5.0.6 on 2024-08-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_communication_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communication',
            old_name='file',
            new_name='location',
        ),
    ]
