# Generated by Django 5.0.6 on 2024-08-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_rename_file_communication_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='location',
            field=models.FileField(upload_to='static/communication/'),
        ),
    ]
