# Generated by Django 5.0.6 on 2024-08-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_communication_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='card_status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('blocked', 'Blocked')], default='pending', max_length=20),
        ),
    ]
