# Generated by Django 5.0.6 on 2024-08-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_appointment_card_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
