# Generated by Django 5.0.6 on 2024-08-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
