# Generated by Django 5.0.6 on 2024-08-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_contactus_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='username',
            new_name='name',
        ),
    ]
