# Generated by Django 5.0.6 on 2024-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingidcard',
            name='date_found',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
