# Generated by Django 5.0.6 on 2024-09-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_missingidcard_date_found'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingidcard',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
    ]
