# Generated by Django 5.0.6 on 2024-09-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_policestation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoliceStation',
        ),
    ]
