# Generated by Django 5.0.6 on 2024-09-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='receipt_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
