# Generated by Django 5.0.6 on 2024-10-08 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_appointment_receipt_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='communication',
            name='description',
            field=models.TextField(default='welcome'),
        ),
        migrations.AddField(
            model_name='communication',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='communications/'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
