# Generated by Django 5.0.6 on 2024-10-09 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_communication_date_communication_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.document'),
        ),
    ]
